### PR TITLE
Adding venue page

### PR DESCRIPTION
**Pull request by likeajumprope**
attempting to add avenue page

### CODE REVIEW

**Comment by tclose** [comment]
I have added a venues section at the bottom of the page, the data for which can be edited at _data/venues.yml. @likeajumprope & @crnolan can you check it out (a demo is up at my fork, https://tclose.github.io/global2021/) and see if it is what you had in mind/needs any changes?

I was thinking that before it goes live we should add a few venues in there to get it started. @stebo85 could you add in your in-person event at UQ. It looks like there is a bit of interest in having an in person USyd one too so I might but that up when I get it organised.

@likeajumprope were you envisaging that everyone posts a picture of where they are coding from?

**Comment by tclose** [comment]
@crnolan I have spent a bit (too much) time playing around with the css of the modal venue-info page (the one that pops up) but couldn't quite get it how I wanted it, i.e. taking up a bigger section of the screen, but that might be just because it needs a bigger image/more content. So feel free to have a play if you think it needs it

**Comment by likeajumprope** [comment]
@tclose yes, that was the idea, any picture like their city, desk or home.  the aim is mostly to have them practise forking, pushing and pulling

**Comment by tclose** [comment]
I have added BMC as an example venue and played around with the CSS some more. Mostly there now but can't seem to get the modal page contents to take up more of the screen. Any thoughts @crnolan ?

**Comment by crnolan** [comment]
Is this sizing for the pop-up what you meant @tclose?

**Comment by tclose** [comment]
> Is this sizing for the pop-up what you meant @tclose?

yes

**Comment by tclose** [comment]
Oh, I just realised that you had already pushed the change @crnolan, thanks! That was driving me bonkers!

Can you add a UQ venue and you add one for UMelb @likeajumprope and then we can merge it?

**Comment by crnolan** [comment]
How is this going to work for more than three venues? Is it going to automatically break into rows?

**Comment by crnolan** [comment]
> How is this going to work for more than three venues? Is it going to automatically break into rows?

Ahh ignore this, it does indeed.

**Pull request merged**
