### PR TITLE
Adds links to BH hackathon resources

### PR DESCRIPTION
**Pull request by tclose**
Adds links to BH hackathon resources and points the register button to the mattermost channel

### CODE REVIEW

**Comment by crnolan** [comment]
Did you intentionally add webrick to the gem dependencies?

**Comment by tclose** [comment]
Ah, no. I had to add it on my mac to get it to run as a workaround though

**Comment by crnolan** [comment]
Ahh ok, so easiest to leave it there for your testing?

**Comment by tclose** [comment]
Yeah, if it isn't hurting anyone then it would be good to have it there

From: Christopher Nolan ***@***.***>
Date: Wednesday, 10 November 2021 at 3:50 pm
To: brainhack-aus/global2021 ***@***.***>
Cc: Tom Close ***@***.***>, Author ***@***.***>
Subject: Re: [brainhack-aus/global2021] Adds links to BH hackathon resources (PR #2)

Ahh ok, so easiest to leave it there for your testing?

**Review by crnolan — APPROVED** [review]
Looks great then!

**Pull request merged**
